"""
hypatia.py — Star Map / Celestarium
=====================================
Metis Toolbox | Anti-Legion: ONE JOB

Job:         Map where every catalog star and planet sits in the sky right now.
             Planets come via Kepler; stars from the loaded catalog.

Contract:    Hybrid flavor (CONVENTIONS §2, the Morpheus/Metis shape):
               - fetch()      : Kairos-polled snapshot. RAISES if the star
                                catalog is empty (total failure) so Kairos
                                delivers None and the panel shows stale —
                                the normal §2 norm, no deviation.
               - set_preset() : a UI-driven mutation, called synchronously
                                from the panel on click (not a Kairos worker).
             handle() + TOOL_DEFINITION expose get_sky_tonight — a distilled
             "what's notable overhead right now" digest (visible planets and the
             brightest visible stars), NOT the full ~1000-star snapshot fetch()
             returns. Kepler stays out of LLM scope; its planets reach the model
             through this digest.

Source:      hypatia_stars.json / hypatia_constellations.json (generated by
             tools/dev_build_hypatia_catalog.py) at the app root, plus
             config/hypatia_lore.json (hand-curated). All three load once at
             import. No network calls in this module.

Math:        RA/Dec -> Alt/Az via sidereal time + the standard spherical
             trig identity (JD -> GMST -> LST -> hour angle -> alt/az). No
             refraction, no precession, no proper motion — accuracy is a
             small fraction of a degree, invisible at panel scale. Do not
             "improve" this; it is deliberately low-precision. Exposed as one
             internal function taking (ra, dec, lat, lon, unix) so Phase 2's
             kepler.py can reuse it verbatim for planet coordinates.

Upstream:    kairos.py (fetch), panels/hypatia_panel.py (fetch + set_preset)
Downstream:  tools/kepler.py (imports this module for _julian_date/_altaz —
             composed by _build_snapshot(), not called directly by anything
             outside this file)

Requires:    math, time, json, os, logging (stdlib only).
"""

import json
import logging
import math
import os
import sys
import time
from typing import Any

# Hypatia reaches UP to app-root themis.py for the observer's lat/lon (the
# Settings tab), read per snapshot so an edit applies on the next Kairos tick.
# Guarded-path pattern (callimachus.py) for a bare `python tools/hypatia.py` —
# placed above `from tools import kepler` so that sibling import also resolves
# in the standalone case (Kairos, tests, and felhaven already have it on path).
if __name__ == "__main__":
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from tools import kepler

import themis

log = logging.getLogger("METIS.hypatia")

# ── Location ──────────────────────────────────────────────────────────────────
# Decimal degrees. North/East positive. The live location is Themis's (Settings
# tab / felhaven_settings.json), read per snapshot in _build_snapshot(). These
# constants are only the FAIL-SOFT DEFAULTS (== Themis's own) — kept because
# tests and kepler.py's __main__ reference them as a fixed sky anchor.
HYPATIA_LAT = 51.4779
HYPATIA_LON = 0.0

# Latitude presets — teaching mode. Longitude stays the observer's own so the
# sky's *timing* is always honest; only latitude jumps.
PRESETS = {
    "current":    HYPATIA_LAT,
    "north_pole":  90.0,
    "equator":      0.0,
    "south_pole": -90.0,
}

# Wake-on-current: never persisted, resets to "current" every launch.
# Written only from the Tk main thread (panel click), read by the Kairos
# worker thread (fetch()) — a single string assignment is atomic under the
# GIL, the same contract style Morpheus documents. set_preset() computes
# synchronously on the main thread; the math below is single-digit
# milliseconds for ~1000 stars, which is why it doesn't need a thread.
_active_preset = "current"

# ── Paths (anchored to __file__, app root = one dir up from tools/) ──────────
_APP_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_STARS_PATH = os.path.join(_APP_ROOT, "hypatia_stars.json")
_CONSTELLATIONS_PATH = os.path.join(_APP_ROOT, "hypatia_constellations.json")
_LORE_PATH = os.path.join(_APP_ROOT, "config", "hypatia_lore.json")


# ── Loaders ───────────────────────────────────────────────────────────────────
# Take an explicit path so tests can call them directly against a temp or
# missing file, separate from the one-time module-level load below.

def _load_stars(path: str) -> dict[int, dict[str, Any]]:
    """hip_id -> {"name", "mag", "ra", "dec"}. [] / {} default on any failure —
    never raises, never crashes the panel (CONVENTIONS §3)."""
    try:
        with open(path, encoding="utf-8") as f:
            raw = json.load(f)["stars"]
        return {s["id"]: s for s in raw}
    except Exception as e:
        log.warning(f"hypatia: could not load star catalog ({path}): {e}")
        return {}


def _load_constellations(path: str) -> list[dict[str, Any]]:
    try:
        with open(path, encoding="utf-8") as f:
            constellations: list[dict[str, Any]] = json.load(f)["constellations"]
            return constellations
    except Exception as e:
        log.warning(f"hypatia: could not load constellation catalog ({path}): {e}")
        return []


def _load_lore(path: str) -> dict[str, Any]:
    """abbr -> blurb. Missing/malformed file degrades to {} — every
    constellation then simply carries "lore": "" (graceful by default)."""
    try:
        with open(path, encoding="utf-8") as f:
            lore: dict[str, Any] = json.load(f)["lore"]
            return lore
    except Exception as e:
        log.warning(f"hypatia: could not load lore file ({path}): {e}")
        return {}


_STARS = _load_stars(_STARS_PATH)
_CONSTELLATIONS = _load_constellations(_CONSTELLATIONS_PATH)
_LORE = _load_lore(_LORE_PATH)

# Merge lore into each constellation once at import — static passthrough,
# never re-read per fetch() (same philosophy as Aura's astronomy block).
for _c in _CONSTELLATIONS:
    _c["lore"] = _LORE.get(_c["abbr"], "")


# ── The math ──────────────────────────────────────────────────────────────────

def _julian_date(unix: float) -> float:
    return unix / 86400.0 + 2440587.5


def _gmst_deg(jd: float) -> float:
    return (280.46061837 + 360.98564736629 * (jd - 2451545.0)) % 360.0


def _altaz(ra: float, dec: float, lat: float, lon: float, unix: float) -> tuple[float, float]:
    """
    RA/Dec (degrees, J2000) -> (alt, az) in degrees for an observer at
    (lat, lon) at the given unix timestamp. az is measured from North,
    through East, normalized to [0, 360). No refraction, precession, or
    proper motion (see module docstring) — Phase 2 reuses this verbatim.
    """
    jd = _julian_date(unix)
    lst_deg = (_gmst_deg(jd) + lon) % 360.0
    h = math.radians(lst_deg - ra)
    dec_r = math.radians(dec)
    lat_r = math.radians(lat)

    sin_alt = math.sin(dec_r) * math.sin(lat_r) + math.cos(dec_r) * math.cos(lat_r) * math.cos(h)
    sin_alt = max(-1.0, min(1.0, sin_alt))
    alt = math.degrees(math.asin(sin_alt))

    az = math.degrees(math.atan2(
        -math.cos(dec_r) * math.sin(h),
        math.sin(dec_r) * math.cos(lat_r) - math.cos(dec_r) * math.sin(lat_r) * math.cos(h),
    ))
    az = az % 360.0
    return alt, az


def _lst_deg(lon: float, unix: float) -> float:
    return (_gmst_deg(_julian_date(unix)) + lon) % 360.0


# ── Mutation contract ─────────────────────────────────────────────────────────

def set_preset(name: str) -> dict[str, Any]:
    """
    Switch the active latitude preset and return a fresh snapshot (same shape
    as fetch()) so the panel can redraw immediately instead of waiting for the
    next Kairos tick. Unknown name -> no-op, returns a snapshot at the current
    preset.
    """
    global _active_preset
    if name in PRESETS:
        _active_preset = name
    return _build_snapshot(time.time())


# ── Contract ──────────────────────────────────────────────────────────────────

def _build_snapshot(unix: float) -> dict[str, Any]:
    if not _STARS:
        raise RuntimeError("hypatia: star catalog is empty")

    # "current" tracks the live Settings lat/lon; the teaching presets are fixed
    # latitudes. Longitude is always the observer's own (Settings) so the sky's
    # timing stays honest even when a preset jumps latitude for teaching.
    lon = themis.longitude()
    lat = themis.latitude() if _active_preset == "current" else PRESETS[_active_preset]
    lst = _lst_deg(lon, unix)

    stars_out = {}
    for hip, star in _STARS.items():
        alt, az = _altaz(star["ra"], star["dec"], lat, lon, unix)
        stars_out[hip] = {
            "name": star.get("name"),
            "mag": star["mag"],
            "alt": round(alt, 3),
            "az": round(az, 3),
        }

    constellations_out = [
        {"abbr": c["abbr"], "name": c["name"], "lore": c["lore"], "lines": c["lines"]}
        for c in _CONSTELLATIONS
    ]

    return {
        "generated_unix": unix,
        "lst_deg": round(lst, 4),
        "preset": _active_preset,
        "stars": stars_out,
        "constellations": constellations_out,
        "planets": kepler.positions(unix, lat, lon),   # Phase 2: the five classical planets
    }


def fetch() -> dict[str, Any]:
    """Kairos entry point. Raises on total catalog failure (empty star set) —
    Kairos catches it and delivers None so the panel shows stale."""
    return _build_snapshot(time.time())


# ── LLM tool contract ─────────────────────────────────────────────────────────
# _build_snapshot() returns ~1000 stars — far too much for a prompt. handle()
# distills it to "what's notable overhead right now": visible planets and the
# brightest visible stars, each with a compass direction and altitude.

_COMPASS_16 = ["N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE",
               "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"]


def _compass(az: float) -> str:
    """Azimuth in degrees (from North, through East) -> 16-point compass name."""
    return _COMPASS_16[int(((az % 360.0) + 11.25) // 22.5) % 16]


TOOL_DEFINITION = {
    "type": "function",
    "function": {
        "name": "get_sky_tonight",
        "description": (
            "Returns what is currently above the horizon for the dashboard's "
            "location: which of the five classical planets are visible (with "
            "direction and altitude) and the brightest visible stars. Call when "
            "the user asks what's in the sky, what's overhead, whether a planet "
            "is up, or what they can see right now."
        ),
        "parameters": {"type": "object", "properties": {}, "required": []},
    },
}


def handle() -> dict[str, Any]:
    """Toolbox entry: a compact 'what's up now' digest. Never raises — an empty
    catalog degrades to an error dict."""
    try:
        snap = _build_snapshot(time.time())
    except Exception as e:
        log.warning(f"Hypatia: sky snapshot failed: {e}")
        return {"error": "sky_unavailable"}

    planets_up = [
        {"name": p["name"], "glyph": p["glyph"],
         "altitude_deg": round(p["alt"], 1), "direction": _compass(p["az"])}
        for p in snap["planets"] if p["alt"] > 0
    ]

    visible = [s for s in snap["stars"].values() if s["alt"] > 0]
    visible.sort(key=lambda s: s["mag"])        # brightest (lowest magnitude) first
    brightest = [
        {"name": s["name"] or "(unnamed)", "magnitude": s["mag"],
         "altitude_deg": round(s["alt"], 1), "direction": _compass(s["az"])}
        for s in visible[:6]
    ]

    return {
        "preset":              snap["preset"],
        "stars_above_horizon": len(visible),
        "planets_visible":     planets_up,
        "brightest_stars":     brightest,
    }


# ── Standalone test ───────────────────────────────────────────────────────────

if __name__ == "__main__":
    snap = fetch()
    print(f"[Hypatia] {len(snap['stars'])} stars | preset={snap['preset']} | "
          f"LST={snap['lst_deg']:.2f}deg")
    visible = [(hip, s) for hip, s in snap["stars"].items() if s["alt"] > 0]
    if visible:
        hip, brightest = min(visible, key=lambda kv: kv[1]["mag"])
        name = brightest["name"] or f"HIP {hip}"
        print(f"[Hypatia] Brightest visible: {name} "
              f"(alt={brightest['alt']:.1f}, az={brightest['az']:.1f}, mag={brightest['mag']})")
    else:
        print("[Hypatia] No stars currently above the horizon.")
